// Mock responses for when the API is unavailable
export const mockResponses = {
  explain: {
    math: "Mathematics can seem complex, but it's really about patterns and relationships between numbers and quantities. Think of it as a language that describes the world around us in a precise way.\n\nFor example, algebra is about finding unknown values. If you know that x + 5 = 10, you can work backward to find that x must be 5. It's like a puzzle where you use what you know to find what you don't know.\n\nGeometry studies shapes and spaces. The formula for the area of a circle (πr²) tells us that the space inside a circle depends on the square of its radius. So a circle with twice the radius has four times the area!\n\nMath builds on itself - each concept is a stepping stone to more advanced ideas. Start with the basics, practice regularly, and don't be afraid to ask questions when you're stuck.",
    science:
      "Science is a systematic way of understanding the natural world through observation and experimentation. It's like being a detective, gathering evidence to solve the mysteries of how things work!\n\nThe scientific method is the foundation of all science. It involves making observations, asking questions, forming hypotheses (educated guesses), testing through experiments, analyzing results, and drawing conclusions.\n\nFor example, if you notice plants growing better near a window, you might hypothesize that light helps plants grow. You could test this by placing identical plants in different lighting conditions and measuring their growth over time.\n\nScience is divided into branches like biology (study of living things), chemistry (study of matter and its interactions), and physics (study of energy and forces). These branches often overlap - for instance, biochemistry explores the chemistry of living organisms.\n\nThe beauty of science is that it's always evolving as we make new discoveries and refine our understanding of the world.",
    history:
      "History is the study of past events and how they've shaped our present world. Think of it as a giant story with countless interconnected characters and plot lines!\n\nUnderstanding history helps us see patterns in human behavior, learn from past mistakes, and appreciate how societies have developed over time. It's not just about memorizing dates and names, but understanding the 'why' behind events.\n\nFor example, World War I (1914-1918) wasn't just a random conflict - it resulted from nationalism, imperialism, militarism, and a complex web of alliances. These tensions built up over decades before exploding into global conflict.\n\nWhen studying history, try to connect events rather than viewing them in isolation. The Industrial Revolution led to new social classes, which influenced political movements, which shaped government policies, and so on.\n\nRemember that history is often written by the victors, so it's important to consider multiple perspectives and primary sources when possible.",
    default:
      "Learning new subjects can sometimes feel overwhelming, but breaking them down into smaller, manageable concepts makes them much easier to understand.\n\nStart by identifying the fundamental principles or building blocks of the subject. These core ideas usually support everything else you'll learn.\n\nMake connections between new information and things you already know. Our brains learn best when we can relate new knowledge to existing mental frameworks.\n\nUse analogies and real-world examples to make abstract concepts more concrete. For instance, if you're learning about electrical current, you might compare it to water flowing through pipes.\n\nDon't be afraid to ask 'why' and 'how' questions. Understanding the reasoning behind concepts is more valuable than memorizing facts.\n\nFinally, teach what you've learned to someone else (or even to an imaginary student). Explaining concepts in your own words reveals gaps in your understanding and reinforces your knowledge.",
  },
  summarize: {
    math: "# Mathematics Summary\n\n## Core Concepts\n- Mathematics is the study of numbers, quantities, shapes, and patterns\n- Built on axioms (basic assumptions) and logical reasoning\n- Divided into various branches including arithmetic, algebra, geometry, calculus, and statistics\n\n## Key Mathematical Principles\n- **Number Systems**: Natural numbers, integers, rational numbers, real numbers, complex numbers\n- **Operations**: Addition, subtraction, multiplication, division, exponentiation\n- **Algebraic Thinking**: Using variables to represent unknown values and solve equations\n- **Geometric Concepts**: Points, lines, angles, shapes, and their properties\n- **Calculus**: Study of continuous change, including differentiation and integration\n- **Statistics**: Collection, analysis, interpretation, and presentation of data\n\n## Problem-Solving Approach\n1. Understand the problem clearly\n2. Identify relevant information and formulas\n3. Develop a strategy or plan\n4. Execute calculations carefully\n5. Verify the solution makes sense\n\n## Applications\n- Science and engineering\n- Economics and finance\n- Computer science and technology\n- Medicine and healthcare\n- Social sciences and everyday decision-making",
    science:
      "# Science Summary Notes\n\n## Definition and Nature of Science\n- Systematic study of the natural world through observation and experimentation\n- Self-correcting process that revises theories based on new evidence\n- Relies on empirical evidence rather than opinion or belief\n\n## The Scientific Method\n1. **Observation**: Notice something in the natural world\n2. **Question**: Ask about what you've observed\n3. **Hypothesis**: Propose a testable explanation\n4. **Prediction**: What should happen if the hypothesis is correct?\n5. **Experimentation**: Test the prediction\n6. **Analysis**: Examine the results\n7. **Conclusion**: Accept, modify, or reject the hypothesis\n\n## Major Branches of Science\n- **Physical Sciences**: Physics, Chemistry, Astronomy, Earth Science\n- **Life Sciences**: Biology, Ecology, Zoology, Botany\n- **Social Sciences**: Psychology, Sociology, Anthropology\n\n## Key Scientific Principles\n- **Causality**: Cause and effect relationships\n- **Reproducibility**: Results should be consistent when experiments are repeated\n- **Falsifiability**: Scientific claims must be testable and potentially disprovable\n- **Parsimony**: Simpler explanations are preferred (Occam's Razor)\n\n## Scientific Literacy Skills\n- Distinguishing between correlation and causation\n- Recognizing bias and controlling variables\n- Understanding statistical significance\n- Evaluating sources of scientific information",
    history:
      "# History Study Notes\n\n## Studying History: Key Concepts\n- History is the study of past events and their impact on human development\n- Involves analysis of primary sources (created during the time period) and secondary sources (interpretations)\n- Requires understanding of chronology, causation, continuity, and change\n\n## Historical Thinking Skills\n- **Chronological Reasoning**: Understanding sequence and time periods\n- **Contextualization**: Placing events in their proper historical context\n- **Causation Analysis**: Identifying immediate and underlying causes and effects\n- **Comparison**: Recognizing similarities and differences across time and place\n- **Sourcing**: Evaluating the reliability and perspective of historical evidence\n\n## Major Historical Themes\n- Political developments and governance systems\n- Social structures and daily life\n- Economic systems and trade\n- Cultural and intellectual movements\n- Technological innovations and their impacts\n- Conflict and cooperation between groups\n\n## Historical Research Methods\n1. Identify research questions\n2. Locate relevant primary and secondary sources\n3. Analyze and interpret evidence\n4. Develop historical arguments\n5. Consider multiple perspectives\n\n## Common Pitfalls to Avoid\n- Presentism (judging the past by present standards)\n- Determinism (viewing events as inevitable)\n- Oversimplification of complex historical processes\n- Overreliance on a single source or perspective",
    default:
      "# General Study Topic Summary\n\n## Core Concepts\n- Every field has fundamental principles that form its foundation\n- Understanding these core concepts is essential before advancing to complex topics\n- Concepts are typically interconnected in a logical framework\n\n## Learning Approach\n1. **Build a Framework**: Identify the big ideas and how they relate\n2. **Active Learning**: Engage with material through questions and application\n3. **Chunking**: Break complex information into manageable parts\n4. **Spaced Repetition**: Review material at increasing intervals\n5. **Varied Practice**: Apply knowledge in different contexts\n\n## Study Strategies\n- **Retrieval Practice**: Test yourself frequently\n- **Elaboration**: Explain concepts in your own words\n- **Concrete Examples**: Connect abstract ideas to specific cases\n- **Dual Coding**: Combine verbal and visual learning\n- **Interleaving**: Mix different but related topics\n\n## Critical Thinking Skills\n- Analyzing arguments and evidence\n- Recognizing patterns and relationships\n- Evaluating sources and claims\n- Drawing logical conclusions\n- Applying concepts to new situations\n\n## Effective Note-Taking\n- Organize information hierarchically\n- Use keywords and phrases rather than full sentences\n- Include diagrams, charts, or mind maps\n- Review and revise notes regularly\n- Connect new information to previously learned material",
  },
  flashcards: {
    math: "CARD 1:\nQuestion: What is the Pythagorean theorem?\nAnswer: The square of the hypotenuse of a right triangle equals the sum of the squares of the other two sides (a² + b² = c²).\n\nCARD 2:\nQuestion: What is the difference between mean, median, and mode?\nAnswer: Mean is the average of all values, median is the middle value when ordered, and mode is the most frequently occurring value.\n\nCARD 3:\nQuestion: What is a prime number?\nAnswer: A number greater than 1 that has no positive divisors other than 1 and itself.\n\nCARD 4:\nQuestion: What is the quadratic formula?\nAnswer: x = (-b ± √(b² - 4ac)) / 2a, used to solve equations in the form ax² + bx + c = 0.\n\nCARD 5:\nQuestion: What is a function in mathematics?\nAnswer: A relation between a set of inputs and outputs where each input is related to exactly one output.\n\nCARD 6:\nQuestion: What is the formula for the area of a circle?\nAnswer: A = πr², where r is the radius of the circle.\n\nCARD 7:\nQuestion: What is the definition of a derivative in calculus?\nAnswer: The instantaneous rate of change of a function with respect to one of its variables.\n\nCARD 8:\nQuestion: What is the commutative property?\nAnswer: The order of the operands does not change the result. For example, a + b = b + a and a × b = b × a.",
    science:
      "CARD 1:\nQuestion: What is the difference between a hypothesis and a theory in science?\nAnswer: A hypothesis is a testable explanation for an observation, while a theory is a well-substantiated explanation supported by multiple lines of evidence and testing.\n\nCARD 2:\nQuestion: What are the main components of a cell?\nAnswer: The main components include the cell membrane, cytoplasm, nucleus (in eukaryotes), mitochondria, endoplasmic reticulum, Golgi apparatus, and various other organelles.\n\nCARD 3:\nQuestion: What is Newton's First Law of Motion?\nAnswer: An object at rest stays at rest, and an object in motion stays in motion with the same speed and direction unless acted upon by an unbalanced force.\n\nCARD 4:\nQuestion: What is the difference between an element and a compound?\nAnswer: An element is a pure substance made of only one type of atom, while a compound consists of two or more different elements chemically bonded together.\n\nCARD 5:\nQuestion: What is photosynthesis?\nAnswer: The process by which green plants and some other organisms use sunlight, water, and carbon dioxide to create oxygen and energy-rich organic compounds.\n\nCARD 6:\nQuestion: What is the periodic table?\nAnswer: A tabular arrangement of chemical elements organized by atomic number, electron configuration, and recurring chemical properties.\n\nCARD 7:\nQuestion: What is DNA?\nAnswer: Deoxyribonucleic acid, a molecule that carries the genetic instructions for the development, functioning, growth, and reproduction of all known organisms.\n\nCARD 8:\nQuestion: What is the law of conservation of energy?\nAnswer: Energy cannot be created or destroyed, only transformed from one form to another or transferred from one object to another.",
    history:
      'CARD 1:\nQuestion: What were the main causes of World War I?\nAnswer: The main causes included militarism, alliances, imperialism, and nationalism (often remembered as MAIN), along with the assassination of Archduke Franz Ferdinand as the immediate trigger.\n\nCARD 2:\nQuestion: What was the Renaissance?\nAnswer: A period of European cultural, artistic, political, and scientific "rebirth" that followed the Middle Ages, approximately from the 14th to the 17th century.\n\nCARD 3:\nQuestion: What was the significance of the Industrial Revolution?\nAnswer: It marked a major turning point in history, transforming largely rural, agrarian societies into industrial ones, leading to urbanization, technological innovation, and significant social and economic changes.\n\nCARD 4:\nQuestion: What was the Cold War?\nAnswer: A period of geopolitical tension between the United States and the Soviet Union and their respective allies from approximately 1947 to 1991, characterized by proxy wars, arms race, and ideological competition.\n\nCARD 5:\nQuestion: What was the Magna Carta?\nAnswer: A charter of rights agreed to by King John of England in 1215, establishing that everyone, including the king, was subject to the law and guaranteeing certain rights to individuals.\n\nCARD 6:\nQuestion: What was the significance of the French Revolution?\nAnswer: It overthrew the monarchy, established a republic, catalyzed violent periods of political turmoil, and finally culminated in a dictatorship under Napoleon. It promoted ideas of liberty, equality, and fraternity that influenced modern democratic thought.\n\nCARD 7:\nQuestion: What was the Civil Rights Movement in the United States?\nAnswer: A decades-long struggle by African Americans and their allies to end institutionalized racial discrimination, disenfranchisement, and racial segregation in the United States, primarily active from the 1950s to the late 1960s.\n\nCARD 8:\nQuestion: What was colonialism?\nAnswer: The policy or practice of acquiring full or partial political control over another country, occupying it with settlers, and exploiting it economically, prevalent especially from the 16th to the 20th centuries.',
    default:
      "CARD 1:\nQuestion: What is active learning?\nAnswer: A process where learners engage with the material through reading, writing, discussing, or solving problems, rather than passively listening or memorizing.\n\nCARD 2:\nQuestion: What is the difference between short-term and long-term memory?\nAnswer: Short-term memory temporarily stores information for about 20-30 seconds, while long-term memory can store information for potentially unlimited duration, from days to decades.\n\nCARD 3:\nQuestion: What is metacognition?\nAnswer: Awareness and understanding of one's own thought processes, or \"thinking about thinking,\" which helps improve learning and problem-solving abilities.\n\nCARD 4:\nQuestion: What is the spacing effect in learning?\nAnswer: The phenomenon where learning is more effective when study sessions are spaced out over time, rather than concentrated in a single session (cramming).\n\nCARD 5:\nQuestion: What is confirmation bias?\nAnswer: The tendency to search for, interpret, favor, and recall information in a way that confirms one's preexisting beliefs or hypotheses, while giving less consideration to alternative possibilities.\n\nCARD 6:\nQuestion: What is critical thinking?\nAnswer: The objective analysis and evaluation of an issue in order to form a judgment, involving skills such as analysis, interpretation, inference, explanation, and self-regulation.\n\nCARD 7:\nQuestion: What is the difference between deductive and inductive reasoning?\nAnswer: Deductive reasoning moves from general principles to specific conclusions, while inductive reasoning moves from specific observations to broader generalizations.\n\nCARD 8:\nQuestion: What are cognitive biases?\nAnswer: Systematic patterns of deviation from norm or rationality in judgment that occur due to perceptual distortions, inaccurate judgments, illogical interpretations, or what is broadly called irrationality.",
  },
  quiz: {
    math: "Q1: What is the value of π (pi) to two decimal places?\nA) 3.14\nB) 3.41\nC) 3.12\nD) 3.16\nCorrect Answer: A\nExplanation: Pi (π) is approximately equal to 3.14159..., so rounded to two decimal places it's 3.14.\n\nQ2: Which of the following is a prime number?\nA) 15\nB) 21\nC) 29\nD) 33\nCorrect Answer: C\nExplanation: 29 is only divisible by 1 and itself, making it a prime number. The other options are composite: 15 = 3 × 5, 21 = 3 × 7, and 33 = 3 × 11.\n\nQ3: Solve for x: 2x + 5 = 13\nA) x = 4\nB) x = 5\nC) x = 6\nD) x = 8\nCorrect Answer: A\nExplanation: 2x + 5 = 13 → 2x = 8 → x = 4\n\nQ4: What is the area of a circle with radius 5 units?\nA) 25π square units\nB) 10π square units\nC) 5π square units\nD) 15π square units\nCorrect Answer: A\nExplanation: The area of a circle is πr², where r is the radius. So the area is π × 5² = 25π square units.\n\nQ5: If a triangle has angles measuring 30° and 60°, what is the measure of the third angle?\nA) 30°\nB) 60°\nC) 90°\nD) 120°\nCorrect Answer: C\nExplanation: The sum of angles in a triangle is 180°. So the third angle is 180° - 30° - 60° = 90°.",
    science:
      'Q1: Which of the following is NOT a state of matter?\nA) Solid\nB) Liquid\nC) Gas\nD) Energy\nCorrect Answer: D\nExplanation: The main states of matter are solid, liquid, gas, and plasma. Energy is a property that matter can possess, not a state of matter itself.\n\nQ2: What is the primary function of mitochondria in a cell?\nA) Protein synthesis\nB) Energy production\nC) Cell division\nD) Waste removal\nCorrect Answer: B\nExplanation: Mitochondria are often called the "powerhouses" of the cell because they generate most of the cell\'s supply of ATP (adenosine triphosphate), which is used as a source of chemical energy.\n\nQ3: Which of the following is Newton\'s Second Law of Motion?\nA) For every action, there is an equal and opposite reaction\nB) An object in motion stays in motion unless acted upon by an external force\nC) Force equals mass times acceleration (F = ma)\nD) Energy cannot be created or destroyed\nCorrect Answer: C\nExplanation: Newton\'s Second Law states that the acceleration of an object is directly proportional to the net force acting on it and inversely proportional to its mass, expressed as F = ma.\n\nQ4: What is the chemical symbol for gold?\nA) Go\nB) Gd\nC) Au\nD) Ag\nCorrect Answer: C\nExplanation: The chemical symbol for gold is Au, which comes from the Latin word "aurum."\n\nQ5: Which of the following is NOT a type of electromagnetic radiation?\nA) X-rays\nB) Microwaves\nC) Sound waves\nD) Ultraviolet light\nCorrect Answer: C\nExplanation: Sound waves are mechanical waves that require a medium to travel through, unlike electromagnetic radiation which can travel through a vacuum. X-rays, microwaves, and ultraviolet light are all types of electromagnetic radiation.',
    history:
      'Q1: Which event marked the beginning of World War I?\nA) The assassination of Archduke Franz Ferdinand\nB) The invasion of Poland\nC) The bombing of Pearl Harbor\nD) The Russian Revolution\nCorrect Answer: A\nExplanation: World War I began after the assassination of Archduke Franz Ferdinand of Austria-Hungary by a Serbian nationalist in Sarajevo on June 28, 1914.\n\nQ2: Which ancient civilization built the pyramids at Giza?\nA) Mesopotamians\nB) Greeks\nC) Romans\nD) Egyptians\nCorrect Answer: D\nExplanation: The pyramids at Giza were built by the ancient Egyptians during the Old and Middle Kingdom periods, primarily serving as tombs for pharaohs.\n\nQ3: What was the main goal of the Marshall Plan after World War II?\nA) To rebuild European economies and prevent the spread of communism\nB) To punish Germany for starting the war\nC) To establish the United Nations\nD) To divide Europe into Eastern and Western blocs\nCorrect Answer: A\nExplanation: The Marshall Plan (officially the European Recovery Program) was an American initiative to aid Western Europe after World War II, providing economic support to help rebuild economies and prevent the spread of Soviet communism.\n\nQ4: Which document begins with the phrase "We the People"?\nA) The Declaration of Independence\nB) The Constitution of the United States\nC) The Emancipation Proclamation\nD) The Gettysburg Address\nCorrect Answer: B\nExplanation: The United States Constitution begins with the Preamble, which starts with the phrase "We the People of the United States..."\n\nQ5: Which of the following was NOT one of the Allied Powers during World War II?\nA) United States\nB) Soviet Union\nC) Japan\nD) Great Britain\nCorrect Answer: C\nExplanation: Japan was part of the Axis Powers (along with Nazi Germany and Fascist Italy) during World War II, fighting against the Allied Powers, which included the United States, Soviet Union, and Great Britain.',
    default:
      'Q1: Which learning technique involves testing yourself on material rather than simply reviewing it?\nA) Rote memorization\nB) Passive reading\nC) Retrieval practice\nD) Highlighting\nCorrect Answer: C\nExplanation: Retrieval practice involves actively recalling information from memory rather than passively reviewing it, which has been shown to significantly improve long-term retention.\n\nQ2: What is the "forgetting curve"?\nA) A graph showing how memory improves over time\nB) A theory that we forget things we don\'t want to remember\nC) A graph showing how memory declines over time without reinforcement\nD) The rate at which technology becomes obsolete\nCorrect Answer: C\nExplanation: The forgetting curve, first described by Hermann Ebbinghaus, illustrates how information is lost over time when there is no attempt to retain it. The curve shows that memory decline is exponential, with the sharpest decline occurring in the first few days.\n\nQ3: Which of the following is an example of intrinsic motivation?\nA) Studying to get good grades\nB) Learning a language because you find it interesting\nC) Exercising to lose weight\nD) Working hard to earn a promotion\nCorrect Answer: B\nExplanation: Intrinsic motivation comes from within - doing something because you find it inherently interesting or enjoyable. Learning a language out of personal interest is intrinsically motivated, while the other examples are driven by external rewards or outcomes.\n\nQ4: What is the recommended approach when facing a complex learning task?\nA) Tackle the entire task at once to see the big picture\nB) Break it down into smaller, manageable parts\nC) Focus only on the most difficult aspects\nD) Memorize as much as possible in one session\nCorrect Answer: B\nExplanation: Breaking complex tasks into smaller, manageable chunks (a technique called "chunking") makes learning more effective by preventing cognitive overload and allowing you to master each component before moving on.\n\nQ5: Which of the following best describes the concept of "transfer of learning"?\nA) Moving from one school to another\nB) Applying knowledge learned in one context to a different situation\nC) Transferring notes from one student to another\nD) Changing your major field of study\nCorrect Answer: B\nExplanation: Transfer of learning refers to the ability to apply knowledge, skills, or strategies learned in one context to new situations or problems. It\'s a fundamental goal of education - ensuring that what is learned can be used beyond the specific context in which it was taught.',
  },
}

// Function to get a mock response based on mode and topic
export function getMockResponse(mode: "explain" | "summarize" | "flashcards" | "quiz", topic: string): string {
  const topicLower = topic.toLowerCase()

  // Check if the topic contains any of our predefined topics
  let selectedTopic = "default"

  if (
    topicLower.includes("math") ||
    topicLower.includes("algebra") ||
    topicLower.includes("calculus") ||
    topicLower.includes("geometry")
  ) {
    selectedTopic = "math"
  } else if (
    topicLower.includes("science") ||
    topicLower.includes("biology") ||
    topicLower.includes("chemistry") ||
    topicLower.includes("physics")
  ) {
    selectedTopic = "science"
  } else if (
    topicLower.includes("history") ||
    topicLower.includes("world war") ||
    topicLower.includes("civilization") ||
    topicLower.includes("revolution")
  ) {
    selectedTopic = "history"
  }

  return mockResponses[mode][selectedTopic]
}
